# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 16:44
from __future__ import unicode_literals

import blogs.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_forwarded', models.BooleanField(default=False, verbose_name='is forwarded blog')),
                ('content_text', models.CharField(max_length=200, verbose_name='content text')),
                ('date_blogged', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date blogged')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
            options={
                'ordering': ['-date_blogged'],
                'verbose_name': 'microblog',
                'verbose_name_plural': 'microblogs',
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blogs.models.get_image_path, verbose_name='content image')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.CharField(max_length=200, verbose_name='content_text')),
                ('date_commented', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date commented')),
            ],
            options={
                'ordering': ['-date_commented'],
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.CreateModel(
            name='ForwardRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_forwarded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date forwarded')),
            ],
        ),
        migrations.CreateModel(
            name='LikeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_liked', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date liked')),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='got_likes', to='blogs.Blog', verbose_name='blog')),
            ],
            options={
                'ordering': ['-date_liked'],
            },
        ),
    ]
