# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 16:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likerecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liked', to=settings.AUTH_USER_MODEL, verbose_name='like by (user)'),
        ),
        migrations.AddField(
            model_name='forwardrecord',
            name='forwarded_blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_relation', to='blogs.Blog', verbose_name='forwarded blog'),
        ),
        migrations.AddField(
            model_name='forwardrecord',
            name='forwarder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarded', to=settings.AUTH_USER_MODEL, verbose_name='forwarder'),
        ),
        migrations.AddField(
            model_name='forwardrecord',
            name='from_blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='be_forwarded', to='blogs.Blog', verbose_name='forwarded from (blog)'),
        ),
        migrations.AddField(
            model_name='forwardrecord',
            name='source_blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='be_forwarded_all', to='blogs.Blog', verbose_name='source blog'),
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='blogs.Blog', verbose_name='blog'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented', to=settings.AUTH_USER_MODEL, verbose_name='commenter'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_comments', to='blogs.Comment', verbose_name='parent comment'),
        ),
        migrations.AddField(
            model_name='blogimage',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_images', to='blogs.Blog', verbose_name='blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='source_blog',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_blogs', to='blogs.Blog', verbose_name='source blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='blogger'),
        ),
    ]
