# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 16:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[\\w\\u4e00-\\u9fa5]+$', 'Please enter a real name', code='invalid_realname')], verbose_name='realname')),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='sex')),
                ('bio', models.CharField(blank=True, help_text='Biography', max_length=60, verbose_name='bio')),
            ],
            options={
                'verbose_name': 'basic profile of bloguser',
            },
        ),
        migrations.CreateModel(
            name='FollowRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_followed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date followed')),
            ],
            options={
                'verbose_name': 'Relationship of follow',
            },
        ),
    ]
