# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 08:33
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20160715_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[\\w\\u4e00-\\u9fa5]+$', 'Please enter a real name', code='invalid_realname')], verbose_name='realname')),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='sex')),
                ('bio', models.CharField(blank=True, help_text='Biography', max_length=60, verbose_name='bio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'basic profile of bloguser',
            },
        ),
    ]
